### ISSUE TITLE
Erroneous NC 2.x dependency

### ISSUE THREAD

**Issue by fritzmg** [Kuestenschmiede/ProjectsBundle#16]
On  2024-03-29 version 4.0.40 was tagged which included the following in its `composer.json`:

```json
"terminal42/notification_center": "^1.6 || ^2.0",
```

This now causes NC 2.x to be installed together with other `con4gis` packages. The fact that you released `4.0.41` where you removed that does not actually help as Composer will still allow a `composer.json` like this for example:

```json
    "require": {
        …
        "terminal42/notification_center": "^2.0",
        "con4gis/reservation": "^3.6"
    },
```

The only way to have properly fixed this is by making the `4.0.41` release _actually_ support NC 2.x (or rather now a subsequent `4.0.42` or `4.1.0` release) - but that is likely a lot of effort.

You could, in this case, also delete the `4.0.40` tag from the repository. This is frowned upon and should not be done in general - but in this case might do more good than harm.

**Comment by coastforge-mei** [comment]
Thanks for the tip. The integration of the 2.x was unfortunately a bit overzealous. I removed the 4.0.40 tag.
